name = "Perpendicular 2.0"
author = "The Parallel Team"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c38b8821a0c54d8b53e24c26e762be985ca0f8e6b915ab93862489713ae73a78"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = []
