name = "Perpendicular 2.0"
author = "The Parallel Team"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89698747b81e576d7ca108c8adaa184190d396d37eb87555f56c21f6fcea52bc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
