name = "Perpendicular 2.0"
author = "The Parallel Team"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a956b251a4c71934b6237b5d41007f0304bc38d8a942e863583470f9314c299"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = []
